-- items table creation with camelCase column names
CREATE TABLE IF NOT EXISTS items (
  "id" VARCHAR(255) PRIMARY KEY,
  "name" VARCHAR(255) NOT NULL,
  "buyDate" VARCHAR(50),
  "buyFrom" VARCHAR(100),
  "buyPrice" NUMERIC,
  "buyCurrency" VARCHAR(10),
  "category" VARCHAR(100),
  "costWash" NUMERIC DEFAULT 0,
  "costRepair" NUMERIC DEFAULT 0,
  "costShip" NUMERIC DEFAULT 0,
  "costDuty" NUMERIC DEFAULT 0,
  "totalCost" NUMERIC DEFAULT 0,
  "sellerName" VARCHAR(255),
  "sellerPhone" VARCHAR(100),
  "sellerTrackingNum" VARCHAR(100),
  "isReceived" BOOLEAN DEFAULT FALSE,
  "status" VARCHAR(50) DEFAULT 'selling',
  "soldDate" VARCHAR(50),
  "soldVia" VARCHAR(100),
  "soldPrice" NUMERIC,
  "soldCurrency" VARCHAR(10),
  "deliveryName" VARCHAR(255),
  "deliveryAddr" TEXT,
  "deliveryPhone" VARCHAR(100),
  "trackingNum" VARCHAR(100),
  "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
